import React from 'react';
import Head from 'next/head';

export default function Contact() {
    return (
        <>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                Site
            </main>
        </>
    );
}
